# Generated by Django 3.2.9 on 2022-01-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=150, verbose_name='Название проекта')),
                ('Content', models.TextField(verbose_name='Описание проекта')),
                ('CreatedAt', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('Status', models.CharField(choices=[('published', 'Опубликовано'), ('offered', 'Предложено'), ('processing', 'Выполняется'), ('done', 'Готово')], default='offered', max_length=40, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=150, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskName', models.CharField(max_length=200, verbose_name='Задача')),
                ('Content', models.TextField(verbose_name='Описание')),
                ('Done', models.BooleanField(verbose_name='Выполнено')),
                ('CreatedAt', models.DateField(verbose_name='Дата создания')),
                ('DateTo', models.DateField(verbose_name='Выполнить к')),
                ('ProjectRel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['DateTo', 'ProjectRel'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject', verbose_name='Предмет'),
        ),
    ]
