# Generated by Django 3.2.9 on 2022-01-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='Project Files', verbose_name='Файл проекта')),
                ('Name', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('Size', models.IntegerField(default=32, verbose_name='Размер')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
