# Generated by Django 3.2.9 on 2022-01-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_projectfiles_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfiles',
            name='Name',
        ),
    ]
