# Generated by Django 3.2.9 on 2022-01-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_projectfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Author',
            field=models.CharField(blank=True, max_length=200, verbose_name='Автор'),
        ),
    ]
