# Generated by Django 3.2.9 on 2022-01-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Summury',
            field=models.CharField(blank=True, max_length=200, verbose_name='Краткое описание'),
        ),
    ]
