# Generated by Django 3.2.9 on 2022-01-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220112_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectFiles',
        ),
    ]
