# Generated by Django 3.2.9 on 2022-01-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_projectfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Project',
            field=models.ManyToManyField(null=True, to='app.Project'),
        ),
    ]
