# Generated by Django 3.2.9 on 2022-01-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_userprofile_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Project',
            field=models.ManyToManyField(blank=True, null=True, to='app.Project'),
        ),
    ]
